[project]
name = "multifunctional-fireguard-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pyqt6>=6.11.0",
    "requests>=2.33.1",
    "ultralytics>=8.4.34",
]
